name: ease_studyante_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner: ^5.4.0
  flutter_bloc: ^8.1.4
  motion_tab_bar: ^2.0.4
  dio: ^5.4.1
  top_snackbar_flutter: ^3.1.0
  collection: ^1.17.1
  equatable: ^2.0.5
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  gap: ^3.0.1
  email_validator: ^2.1.17
  flutter_progress_hud: ^2.0.2
  animated_bottom_navigation_bar: ^1.3.3
  page_transition: ^2.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon/
    - assets/lottie/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Bold.ttf
        - asset: assets/fonts/JosefinSans-ExtraLight.ttf
        - asset: assets/fonts/JosefinSans-Light.ttf
        - asset: assets/fonts/JosefinSans-Medium.ttf
        - asset: assets/fonts/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
        - asset: assets/fonts/JosefinSans-Thin.ttf
          style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_gen:
  output: lib/gen/ 
  line_length: 80 
  integrations:
    flutter_svg: true
    lottie: true

  # integrate colors here
  colors:
    inputs:
      - assets/color/colors.xml

flutter_icons:
  image_path: "assets/app_icon/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ff3d3d"

 
  android_12:
    image: assets/app_icon/ic_launcher.png
    color: "#ff3d3d"
